version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: "1" # maximum 1 core allocated
          memory: 512M # maximum 512MB memory allocated
  database:
    image: mysql:8.0
    container_name: community-database
    environment:
      MYSQL_DATABASE: community
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: jongwanra
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=jongwanra" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2" # maximum 2 cores allocated
          memory: 2GB # maximum 2GB memory allocated


volumes:
  mysql_data:
  redis_data:

networks:
  monitoring:
    driver: bridge
