spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:3306/community?useSSL=false&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: ${RDS_PASSWORD:jongwanra}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 20
      maximum-pool-size: 20
      max-lifetime: 1797000 # 29m 57s
      connection-timeout: 5000 # 5s

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.MySQL8Dialect # why use it?
    open-in-view: false


  sql:
    init:
      mode: never
      platform: local
  data:
    redis:
      host: localhost
      port: 6379

